// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XSD_TYPE_COMPLEX_SCALE_SET_PIMPL_HH
#define CXX___XSD_TYPE_COMPLEX_SCALE_SET_PIMPL_HH

#include "complex-scale_set-pskel.hh"

#include "simple-types-pimpl.hh"

#include "complex-scale-pimpl.hh"

namespace tmxsd
{
  class scale_set_pimpl: public virtual scale_set_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    name (const std::string&);

    virtual void
    comment (const std::string&);

    virtual void
    scale (const ::tmxsd::scale&);

    virtual void
    scale_set_id (unsigned int);

    virtual void
    datetime (const std::string&);

    virtual void
    is_valid (bool);

    virtual ::tmxsd::scale_set
    post_scale_set ();
  };
}

#endif // CXX___XSD_TYPE_COMPLEX_SCALE_SET_PIMPL_HH
