// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-bin-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // bin_pimpl
  //

  void bin_pimpl::
  pre ()
  {
  }

  void bin_pimpl::
  number (unsigned int number)
  {
    std::cout << "number: " << number << std::endl;
  }

  void bin_pimpl::
  minimum (const std::string& minimum)
  {
    // TODO
    //
  }

  void bin_pimpl::
  maximum (const std::string& maximum)
  {
    // TODO
    //
  }

  void bin_pimpl::
  bin_id (unsigned int bin_id)
  {
    // TODO
    //
  }

  void bin_pimpl::
  scale_id (unsigned int scale_id)
  {
    // TODO
    //
  }

  ::tmxsd::bin bin_pimpl::
  post_bin ()
  {
    // TODO
    //
    // return ... ;
  }
}

