// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-ext_signal-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // ext_signal_pimpl
  //

  void ext_signal_pimpl::
  pre ()
  {
  }

  void ext_signal_pimpl::
  name (const std::string& name)
  {
    // TODO
    //
  }

  void ext_signal_pimpl::
  system (const std::string& system)
  {
    // TODO
    //
  }

  void ext_signal_pimpl::
  cable (unsigned int cable)
  {
    std::cout << "cable: " << cable << std::endl;
  }

  void ext_signal_pimpl::
  channel (unsigned int channel)
  {
    std::cout << "channel: " << channel << std::endl;
  }

  void ext_signal_pimpl::
  description (const std::string& description)
  {
    // TODO
    //
  }

  void ext_signal_pimpl::
  label (const std::string& label)
  {
    // TODO
    //
  }

  void ext_signal_pimpl::
  ext_signal_id (unsigned int ext_signal_id)
  {
    // TODO
    //
  }

  void ext_signal_pimpl::
  datetime (const std::string& datetime)
  {
    // TODO
    //
  }

  ::tmxsd::ext_signal ext_signal_pimpl::
  post_ext_signal ()
  {
    // TODO
    //
    // return ... ;
  }
}

