// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-object_requirement-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // object_requirement_pimpl
  //

  void object_requirement_pimpl::
  pre ()
  {
  }

  void object_requirement_pimpl::
  name (const std::string& name)
  {
    // TODO
    //
  }

  void object_requirement_pimpl::
  type (const std::string& type)
  {
    // TODO
    //
  }

  void object_requirement_pimpl::
  comparison_operator (const std::string& comparison_operator)
  {
    // TODO
    //
  }

  void object_requirement_pimpl::
  threshold (const std::string& threshold)
  {
    // TODO
    //
  }

  void object_requirement_pimpl::
  bx_offset (int bx_offset)
  {
    std::cout << "bx_offset: " << bx_offset << std::endl;
  }

  void object_requirement_pimpl::
  comment (const std::string& comment)
  {
    // TODO
    //
  }

  void object_requirement_pimpl::
  requirement_id (unsigned int requirement_id)
  {
    // TODO
    //
  }

  void object_requirement_pimpl::
  datetime (const std::string& datetime)
  {
    // TODO
    //
  }

  ::tmxsd::object_requirement object_requirement_pimpl::
  post_object_requirement ()
  {
    // TODO
    //
    // return ... ;
  }
}

