// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XSD_TYPE_COMPLEX_EXT_SIGNAL_SET_PIMPL_HH
#define CXX___XSD_TYPE_COMPLEX_EXT_SIGNAL_SET_PIMPL_HH

#include "complex-ext_signal_set-pskel.hh"

#include "complex-ext_signal-pimpl.hh"

namespace tmxsd
{
  class ext_signal_set_pimpl: public virtual ext_signal_set_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    name (const std::string&);

    virtual void
    comment (const std::string&);

    virtual void
    ext_signal (const ::tmxsd::ext_signal&);

    virtual void
    ext_signal_set_id (unsigned int);

    virtual void
    datetime (const std::string&);

    virtual void
    is_valid (bool);

    virtual ::tmxsd::ext_signal_set
    post_ext_signal_set ();
  };
}

#endif // CXX___XSD_TYPE_COMPLEX_EXT_SIGNAL_SET_PIMPL_HH
