// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-external_requirement-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // external_requirement_pimpl
  //

  void external_requirement_pimpl::
  pre ()
  {
  }

  void external_requirement_pimpl::
  name (const std::string& name)
  {
    // TODO
    //
  }

  void external_requirement_pimpl::
  bx_offset (int bx_offset)
  {
    std::cout << "bx_offset: " << bx_offset << std::endl;
  }

  void external_requirement_pimpl::
  comment (const std::string& comment)
  {
    // TODO
    //
  }

  void external_requirement_pimpl::
  requirement_id (unsigned int requirement_id)
  {
    // TODO
    //
  }

  void external_requirement_pimpl::
  ext_signal_id (unsigned int ext_signal_id)
  {
    // TODO
    //
  }

  void external_requirement_pimpl::
  datetime (const std::string& datetime)
  {
    // TODO
    //
  }

  ::tmxsd::external_requirement external_requirement_pimpl::
  post_external_requirement ()
  {
    // TODO
    //
    // return ... ;
  }
}

