// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-ext_signal_set-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // ext_signal_set_pimpl
  //

  void ext_signal_set_pimpl::
  pre ()
  {
  }

  void ext_signal_set_pimpl::
  name (const std::string& name)
  {
    // TODO
    //
  }

  void ext_signal_set_pimpl::
  comment (const std::string& comment)
  {
    // TODO
    //
  }

  void ext_signal_set_pimpl::
  ext_signal (const ::tmxsd::ext_signal& ext_signal)
  {
    // TODO
    //
  }

  void ext_signal_set_pimpl::
  ext_signal_set_id (unsigned int ext_signal_set_id)
  {
    // TODO
    //
  }

  void ext_signal_set_pimpl::
  datetime (const std::string& datetime)
  {
    // TODO
    //
  }

  void ext_signal_set_pimpl::
  is_valid (bool is_valid)
  {
    std::cout << "is_valid: " << is_valid << std::endl;
  }

  ::tmxsd::ext_signal_set ext_signal_set_pimpl::
  post_ext_signal_set ()
  {
    // TODO
    //
    // return ... ;
  }
}

