// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XSD_TYPE_COMPLEX_EXTERNAL_REQUIREMENT_PIMPL_HH
#define CXX___XSD_TYPE_COMPLEX_EXTERNAL_REQUIREMENT_PIMPL_HH

#include "complex-external_requirement-pskel.hh"

#include "simple-types-pimpl.hh"

namespace tmxsd
{
  class external_requirement_pimpl: public virtual external_requirement_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    name (const std::string&);

    virtual void
    bx_offset (int);

    virtual void
    comment (const std::string&);

    virtual void
    requirement_id (unsigned int);

    virtual void
    ext_signal_id (unsigned int);

    virtual void
    datetime (const std::string&);

    virtual ::tmxsd::external_requirement
    post_external_requirement ();
  };
}

#endif // CXX___XSD_TYPE_COMPLEX_EXTERNAL_REQUIREMENT_PIMPL_HH
