// Copyright (C) 2005-2008 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "complex-scale_set.hxx"

namespace tmxsdtree
{
  // scale_set
  // 

  const scale_set::name_type& scale_set::
  name () const
  {
    return this->name_.get ();
  }

  scale_set::name_type& scale_set::
  name ()
  {
    return this->name_.get ();
  }

  void scale_set::
  name (const name_type& x)
  {
    this->name_.set (x);
  }

  void scale_set::
  name (::std::auto_ptr< name_type > x)
  {
    this->name_.set (x);
  }

  const scale_set::comment_optional& scale_set::
  comment () const
  {
    return this->comment_;
  }

  scale_set::comment_optional& scale_set::
  comment ()
  {
    return this->comment_;
  }

  void scale_set::
  comment (const comment_type& x)
  {
    this->comment_.set (x);
  }

  void scale_set::
  comment (const comment_optional& x)
  {
    this->comment_ = x;
  }

  void scale_set::
  comment (::std::auto_ptr< comment_type > x)
  {
    this->comment_.set (x);
  }

  const scale_set::scale_sequence& scale_set::
  scale () const
  {
    return this->scale_;
  }

  scale_set::scale_sequence& scale_set::
  scale ()
  {
    return this->scale_;
  }

  void scale_set::
  scale (const scale_sequence& s)
  {
    this->scale_ = s;
  }

  const scale_set::scale_set_id_optional& scale_set::
  scale_set_id () const
  {
    return this->scale_set_id_;
  }

  scale_set::scale_set_id_optional& scale_set::
  scale_set_id ()
  {
    return this->scale_set_id_;
  }

  void scale_set::
  scale_set_id (const scale_set_id_type& x)
  {
    this->scale_set_id_.set (x);
  }

  void scale_set::
  scale_set_id (const scale_set_id_optional& x)
  {
    this->scale_set_id_ = x;
  }

  void scale_set::
  scale_set_id (::std::auto_ptr< scale_set_id_type > x)
  {
    this->scale_set_id_.set (x);
  }

  const scale_set::datetime_optional& scale_set::
  datetime () const
  {
    return this->datetime_;
  }

  scale_set::datetime_optional& scale_set::
  datetime ()
  {
    return this->datetime_;
  }

  void scale_set::
  datetime (const datetime_type& x)
  {
    this->datetime_.set (x);
  }

  void scale_set::
  datetime (const datetime_optional& x)
  {
    this->datetime_ = x;
  }

  void scale_set::
  datetime (::std::auto_ptr< datetime_type > x)
  {
    this->datetime_.set (x);
  }

  const scale_set::is_valid_optional& scale_set::
  is_valid () const
  {
    return this->is_valid_;
  }

  scale_set::is_valid_optional& scale_set::
  is_valid ()
  {
    return this->is_valid_;
  }

  void scale_set::
  is_valid (const is_valid_type& x)
  {
    this->is_valid_.set (x);
  }

  void scale_set::
  is_valid (const is_valid_optional& x)
  {
    this->is_valid_ = x;
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace tmxsdtree
{
  // scale_set
  //

  scale_set::
  scale_set (const name_type& name)
  : ::xml_schema::type (),
    name_ (name, ::xml_schema::flags (), this),
    comment_ (::xml_schema::flags (), this),
    scale_ (::xml_schema::flags (), this),
    scale_set_id_ (::xml_schema::flags (), this),
    datetime_ (::xml_schema::flags (), this),
    is_valid_ (::xml_schema::flags (), this)
  {
  }

  scale_set::
  scale_set (const scale_set& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    name_ (x.name_, f, this),
    comment_ (x.comment_, f, this),
    scale_ (x.scale_, f, this),
    scale_set_id_ (x.scale_set_id_, f, this),
    datetime_ (x.datetime_, f, this),
    is_valid_ (x.is_valid_, f, this)
  {
  }

  scale_set::
  scale_set (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    name_ (f, this),
    comment_ (f, this),
    scale_ (f, this),
    scale_set_id_ (f, this),
    datetime_ (f, this),
    is_valid_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void scale_set::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // name
      //
      if (n.name () == "name" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< name_type > r (
          name_traits::create (i, f, this));

        if (!name_.present ())
        {
          this->name (r);
          continue;
        }
      }

      // comment
      //
      if (n.name () == "comment" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< comment_type > r (
          comment_traits::create (i, f, this));

        if (!this->comment ())
        {
          this->comment (r);
          continue;
        }
      }

      // scale
      //
      if (n.name () == "scale" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< scale_type > r (
          scale_traits::create (i, f, this));

        this->scale ().push_back (r);
        continue;
      }

      break;
    }

    if (!name_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "name",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "scale_set_id" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< scale_set_id_type > r (
          scale_set_id_traits::create (i, f, this));

        this->scale_set_id (r);
        continue;
      }

      if (n.name () == "datetime" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< datetime_type > r (
          datetime_traits::create (i, f, this));

        this->datetime (r);
        continue;
      }

      if (n.name () == "is_valid" && n.namespace_ ().empty ())
      {
        this->is_valid (is_valid_traits::create (i, f, this));
        continue;
      }
    }
  }

  scale_set* scale_set::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new scale_set (*this, f, c);
  }

  scale_set::
  ~scale_set ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace tmxsdtree
{
}

#include <ostream>
#include <xsd/cxx/xml/dom/serialization-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace tmxsdtree
{
  void
  operator<< (::xercesc::DOMElement& e, const scale_set& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // name
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "name",
          e));

      s << i.name ();
    }

    // comment
    //
    if (i.comment ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "comment",
          e));

      s << *i.comment ();
    }

    // scale
    //
    for (scale_set::scale_const_iterator
         b (i.scale ().begin ()), n (i.scale ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "scale",
          e));

      s << *b;
    }

    // scale_set_id
    //
    if (i.scale_set_id ())
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "scale_set_id",
          e));

      a << *i.scale_set_id ();
    }

    // datetime
    //
    if (i.datetime ())
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "datetime",
          e));

      a << *i.datetime ();
    }

    // is_valid
    //
    if (i.is_valid ())
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "is_valid",
          e));

      a << *i.is_valid ();
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

