// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XSD_TYPE_COMPLEX_CUT_PIMPL_HH
#define CXX___XSD_TYPE_COMPLEX_CUT_PIMPL_HH

#include "complex-cut-pskel.hh"

#include "simple-types-pimpl.hh"

namespace tmxsd
{
  class cut_pimpl: public virtual cut_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    name (const std::string&);

    virtual void
    object (const std::string&);

    virtual void
    type (const std::string&);

    virtual void
    minimum (const std::string&);

    virtual void
    maximum (const std::string&);

    virtual void
    data (const std::string&);

    virtual void
    comment (const std::string&);

    virtual void
    cut_id (unsigned int);

    virtual void
    datetime (const std::string&);

    virtual ::tmxsd::cut
    post_cut ();
  };
}

#endif // CXX___XSD_TYPE_COMPLEX_CUT_PIMPL_HH
