// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XSD_TYPE_COMPLEX_EXT_SIGNAL_PIMPL_HH
#define CXX___XSD_TYPE_COMPLEX_EXT_SIGNAL_PIMPL_HH

#include "complex-ext_signal-pskel.hh"

#include "simple-types-pimpl.hh"

namespace tmxsd
{
  class ext_signal_pimpl: public virtual ext_signal_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    name (const std::string&);

    virtual void
    system (const std::string&);

    virtual void
    cable (unsigned int);

    virtual void
    channel (unsigned int);

    virtual void
    description (const std::string&);

    virtual void
    label (const std::string&);

    virtual void
    ext_signal_id (unsigned int);

    virtual void
    datetime (const std::string&);

    virtual ::tmxsd::ext_signal
    post_ext_signal ();
  };
}

#endif // CXX___XSD_TYPE_COMPLEX_EXT_SIGNAL_PIMPL_HH
