// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XSD_TYPE_COMPLEX_SCALE_PIMPL_HH
#define CXX___XSD_TYPE_COMPLEX_SCALE_PIMPL_HH

#include "complex-scale-pskel.hh"

#include "simple-types-pimpl.hh"

#include "complex-bin-pimpl.hh"

namespace tmxsd
{
  class scale_pimpl: public virtual scale_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    object (const std::string&);

    virtual void
    type (const std::string&);

    virtual void
    minimum (const std::string&);

    virtual void
    maximum (const std::string&);

    virtual void
    step (const std::string&);

    virtual void
    n_bits (unsigned int);

    virtual void
    comment (const std::string&);

    virtual void
    bin (const ::tmxsd::bin&);

    virtual void
    scale_id (unsigned int);

    virtual void
    datetime (const std::string&);

    virtual void
    n_bins (unsigned int);

    virtual ::tmxsd::scale
    post_scale ();
  };
}

#endif // CXX___XSD_TYPE_COMPLEX_SCALE_PIMPL_HH
