// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-menu-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // menu_pimpl
  //

  void menu_pimpl::
  pre ()
  {
  }

  void menu_pimpl::
  ancestor_id (unsigned int ancestor_id)
  {
    // TODO
    //
  }

  void menu_pimpl::
  name (const std::string& name)
  {
    // TODO
    //
  }

  void menu_pimpl::
  uuid_menu (const std::string& uuid_menu)
  {
    // TODO
    //
  }

  void menu_pimpl::
  uuid_firmware (const std::string& uuid_firmware)
  {
    // TODO
    //
  }

  void menu_pimpl::
  global_tag (const std::string& global_tag)
  {
    // TODO
    //
  }

  void menu_pimpl::
  grammar_version (const std::string& grammar_version)
  {
    // TODO
    //
  }

  void menu_pimpl::
  n_modules (unsigned int n_modules)
  {
    std::cout << "n_modules: " << n_modules << std::endl;
  }

  void menu_pimpl::
  is_valid (bool is_valid)
  {
    std::cout << "is_valid: " << is_valid << std::endl;
  }

  void menu_pimpl::
  is_obsolete (bool is_obsolete)
  {
    std::cout << "is_obsolete: " << is_obsolete << std::endl;
  }

  void menu_pimpl::
  comment (const std::string& comment)
  {
    // TODO
    //
  }

  void menu_pimpl::
  algorithm (const ::tmxsd::algorithm& algorithm)
  {
    // TODO
    //
  }

  void menu_pimpl::
  scale_set (const ::tmxsd::scale_set& scale_set)
  {
    // TODO
    //
  }

  void menu_pimpl::
  ext_signal_set (const ::tmxsd::ext_signal_set& ext_signal_set)
  {
    // TODO
    //
  }

  void menu_pimpl::
  menu_id (unsigned int menu_id)
  {
    // TODO
    //
  }

  void menu_pimpl::
  datetime (const std::string& datetime)
  {
    // TODO
    //
  }

  ::tmxsd::menu menu_pimpl::
  post_menu ()
  {
    // TODO
    //
    // return ... ;
  }
}

