// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-scale_set-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // scale_set_pimpl
  //

  void scale_set_pimpl::
  pre ()
  {
  }

  void scale_set_pimpl::
  name (const std::string& name)
  {
    // TODO
    //
  }

  void scale_set_pimpl::
  comment (const std::string& comment)
  {
    // TODO
    //
  }

  void scale_set_pimpl::
  scale (const ::tmxsd::scale& scale)
  {
    // TODO
    //
  }

  void scale_set_pimpl::
  scale_set_id (unsigned int scale_set_id)
  {
    // TODO
    //
  }

  void scale_set_pimpl::
  datetime (const std::string& datetime)
  {
    // TODO
    //
  }

  void scale_set_pimpl::
  is_valid (bool is_valid)
  {
    std::cout << "is_valid: " << is_valid << std::endl;
  }

  ::tmxsd::scale_set scale_set_pimpl::
  post_scale_set ()
  {
    // TODO
    //
    // return ... ;
  }
}

