// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-scale-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // scale_pimpl
  //

  void scale_pimpl::
  pre ()
  {
  }

  void scale_pimpl::
  object (const std::string& object)
  {
    // TODO
    //
  }

  void scale_pimpl::
  type (const std::string& type)
  {
    // TODO
    //
  }

  void scale_pimpl::
  minimum (const std::string& minimum)
  {
    // TODO
    //
  }

  void scale_pimpl::
  maximum (const std::string& maximum)
  {
    // TODO
    //
  }

  void scale_pimpl::
  step (const std::string& step)
  {
    // TODO
    //
  }

  void scale_pimpl::
  n_bits (unsigned int n_bits)
  {
    std::cout << "n_bits: " << n_bits << std::endl;
  }

  void scale_pimpl::
  comment (const std::string& comment)
  {
    // TODO
    //
  }

  void scale_pimpl::
  bin (const ::tmxsd::bin& bin)
  {
    // TODO
    //
  }

  void scale_pimpl::
  scale_id (unsigned int scale_id)
  {
    // TODO
    //
  }

  void scale_pimpl::
  datetime (const std::string& datetime)
  {
    // TODO
    //
  }

  void scale_pimpl::
  n_bins (unsigned int n_bins)
  {
    std::cout << "n_bins: " << n_bins << std::endl;
  }

  ::tmxsd::scale scale_pimpl::
  post_scale ()
  {
    // TODO
    //
    // return ... ;
  }
}

