// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "complex-ext_signal.hxx"

namespace tmxsdtree
{
  // ext_signal
  // 

  const ext_signal::name_type& ext_signal::
  name () const
  {
    return this->name_.get ();
  }

  ext_signal::name_type& ext_signal::
  name ()
  {
    return this->name_.get ();
  }

  void ext_signal::
  name (const name_type& x)
  {
    this->name_.set (x);
  }

  void ext_signal::
  name (::std::unique_ptr< name_type > x)
  {
    this->name_.set (std::move (x));
  }

  const ext_signal::system_type& ext_signal::
  system () const
  {
    return this->system_.get ();
  }

  ext_signal::system_type& ext_signal::
  system ()
  {
    return this->system_.get ();
  }

  void ext_signal::
  system (const system_type& x)
  {
    this->system_.set (x);
  }

  void ext_signal::
  system (::std::unique_ptr< system_type > x)
  {
    this->system_.set (std::move (x));
  }

  const ext_signal::cable_type& ext_signal::
  cable () const
  {
    return this->cable_.get ();
  }

  ext_signal::cable_type& ext_signal::
  cable ()
  {
    return this->cable_.get ();
  }

  void ext_signal::
  cable (const cable_type& x)
  {
    this->cable_.set (x);
  }

  const ext_signal::channel_type& ext_signal::
  channel () const
  {
    return this->channel_.get ();
  }

  ext_signal::channel_type& ext_signal::
  channel ()
  {
    return this->channel_.get ();
  }

  void ext_signal::
  channel (const channel_type& x)
  {
    this->channel_.set (x);
  }

  const ext_signal::description_optional& ext_signal::
  description () const
  {
    return this->description_;
  }

  ext_signal::description_optional& ext_signal::
  description ()
  {
    return this->description_;
  }

  void ext_signal::
  description (const description_type& x)
  {
    this->description_.set (x);
  }

  void ext_signal::
  description (const description_optional& x)
  {
    this->description_ = x;
  }

  void ext_signal::
  description (::std::unique_ptr< description_type > x)
  {
    this->description_.set (std::move (x));
  }

  const ext_signal::label_optional& ext_signal::
  label () const
  {
    return this->label_;
  }

  ext_signal::label_optional& ext_signal::
  label ()
  {
    return this->label_;
  }

  void ext_signal::
  label (const label_type& x)
  {
    this->label_.set (x);
  }

  void ext_signal::
  label (const label_optional& x)
  {
    this->label_ = x;
  }

  void ext_signal::
  label (::std::unique_ptr< label_type > x)
  {
    this->label_.set (std::move (x));
  }

  const ext_signal::ext_signal_id_optional& ext_signal::
  ext_signal_id () const
  {
    return this->ext_signal_id_;
  }

  ext_signal::ext_signal_id_optional& ext_signal::
  ext_signal_id ()
  {
    return this->ext_signal_id_;
  }

  void ext_signal::
  ext_signal_id (const ext_signal_id_type& x)
  {
    this->ext_signal_id_.set (x);
  }

  void ext_signal::
  ext_signal_id (const ext_signal_id_optional& x)
  {
    this->ext_signal_id_ = x;
  }

  void ext_signal::
  ext_signal_id (::std::unique_ptr< ext_signal_id_type > x)
  {
    this->ext_signal_id_.set (std::move (x));
  }

  const ext_signal::datetime_optional& ext_signal::
  datetime () const
  {
    return this->datetime_;
  }

  ext_signal::datetime_optional& ext_signal::
  datetime ()
  {
    return this->datetime_;
  }

  void ext_signal::
  datetime (const datetime_type& x)
  {
    this->datetime_.set (x);
  }

  void ext_signal::
  datetime (const datetime_optional& x)
  {
    this->datetime_ = x;
  }

  void ext_signal::
  datetime (::std::unique_ptr< datetime_type > x)
  {
    this->datetime_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace tmxsdtree
{
  // ext_signal
  //

  ext_signal::
  ext_signal (const name_type& name,
              const system_type& system,
              const cable_type& cable,
              const channel_type& channel)
  : ::xml_schema::type (),
    name_ (name, this),
    system_ (system, this),
    cable_ (cable, this),
    channel_ (channel, this),
    description_ (this),
    label_ (this),
    ext_signal_id_ (this),
    datetime_ (this)
  {
  }

  ext_signal::
  ext_signal (const ext_signal& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    name_ (x.name_, f, this),
    system_ (x.system_, f, this),
    cable_ (x.cable_, f, this),
    channel_ (x.channel_, f, this),
    description_ (x.description_, f, this),
    label_ (x.label_, f, this),
    ext_signal_id_ (x.ext_signal_id_, f, this),
    datetime_ (x.datetime_, f, this)
  {
  }

  ext_signal::
  ext_signal (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    name_ (this),
    system_ (this),
    cable_ (this),
    channel_ (this),
    description_ (this),
    label_ (this),
    ext_signal_id_ (this),
    datetime_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
      this->parse (p, f);
    }
  }

  void ext_signal::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // name
      //
      if (n.name () == "name" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< name_type > r (
          name_traits::create (i, f, this));

        if (!name_.present ())
        {
          this->name_.set (::std::move (r));
          continue;
        }
      }

      // system
      //
      if (n.name () == "system" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< system_type > r (
          system_traits::create (i, f, this));

        if (!system_.present ())
        {
          this->system_.set (::std::move (r));
          continue;
        }
      }

      // cable
      //
      if (n.name () == "cable" && n.namespace_ ().empty ())
      {
        if (!cable_.present ())
        {
          this->cable_.set (cable_traits::create (i, f, this));
          continue;
        }
      }

      // channel
      //
      if (n.name () == "channel" && n.namespace_ ().empty ())
      {
        if (!channel_.present ())
        {
          this->channel_.set (channel_traits::create (i, f, this));
          continue;
        }
      }

      // description
      //
      if (n.name () == "description" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< description_type > r (
          description_traits::create (i, f, this));

        if (!this->description_)
        {
          this->description_.set (::std::move (r));
          continue;
        }
      }

      // label
      //
      if (n.name () == "label" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< label_type > r (
          label_traits::create (i, f, this));

        if (!this->label_)
        {
          this->label_.set (::std::move (r));
          continue;
        }
      }

      break;
    }

    if (!name_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "name",
        "");
    }

    if (!system_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "system",
        "");
    }

    if (!cable_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "cable",
        "");
    }

    if (!channel_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "channel",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "ext_signal_id" && n.namespace_ ().empty ())
      {
        this->ext_signal_id_.set (ext_signal_id_traits::create (i, f, this));
        continue;
      }

      if (n.name () == "datetime" && n.namespace_ ().empty ())
      {
        this->datetime_.set (datetime_traits::create (i, f, this));
        continue;
      }
    }
  }

  ext_signal* ext_signal::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class ext_signal (*this, f, c);
  }

  ext_signal& ext_signal::
  operator= (const ext_signal& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->name_ = x.name_;
      this->system_ = x.system_;
      this->cable_ = x.cable_;
      this->channel_ = x.channel_;
      this->description_ = x.description_;
      this->label_ = x.label_;
      this->ext_signal_id_ = x.ext_signal_id_;
      this->datetime_ = x.datetime_;
    }

    return *this;
  }

  ext_signal::
  ~ext_signal ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace tmxsdtree
{
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace tmxsdtree
{
  void
  operator<< (::xercesc::DOMElement& e, const ext_signal& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // name
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "name",
          e));

      s << i.name ();
    }

    // system
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "system",
          e));

      s << i.system ();
    }

    // cable
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "cable",
          e));

      s << i.cable ();
    }

    // channel
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "channel",
          e));

      s << i.channel ();
    }

    // description
    //
    if (i.description ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "description",
          e));

      s << *i.description ();
    }

    // label
    //
    if (i.label ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "label",
          e));

      s << *i.label ();
    }

    // ext_signal_id
    //
    if (i.ext_signal_id ())
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "ext_signal_id",
          e));

      a << *i.ext_signal_id ();
    }

    // datetime
    //
    if (i.datetime ())
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "datetime",
          e));

      a << *i.datetime ();
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

