// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XSD_TYPE_COMPLEX_OBJECT_REQUIREMENT_PIMPL_HH
#define CXX___XSD_TYPE_COMPLEX_OBJECT_REQUIREMENT_PIMPL_HH

#include "complex-object_requirement-pskel.hh"

#include "simple-types-pimpl.hh"

namespace tmxsd
{
  class object_requirement_pimpl: public virtual object_requirement_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    name (const std::string&);

    virtual void
    type (const std::string&);

    virtual void
    comparison_operator (const std::string&);

    virtual void
    threshold (const std::string&);

    virtual void
    bx_offset (int);

    virtual void
    comment (const std::string&);

    virtual void
    requirement_id (unsigned int);

    virtual void
    datetime (const std::string&);

    virtual ::tmxsd::object_requirement
    post_object_requirement ();
  };
}

#endif // CXX___XSD_TYPE_COMPLEX_OBJECT_REQUIREMENT_PIMPL_HH
