// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "complex-cut-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // cut_pimpl
  //

  void cut_pimpl::
  pre ()
  {
  }

  void cut_pimpl::
  name (const std::string& name)
  {
    // TODO
    //
  }

  void cut_pimpl::
  object (const std::string& object)
  {
    // TODO
    //
  }

  void cut_pimpl::
  type (const std::string& type)
  {
    // TODO
    //
  }

  void cut_pimpl::
  minimum (const std::string& minimum)
  {
    // TODO
    //
  }

  void cut_pimpl::
  maximum (const std::string& maximum)
  {
    // TODO
    //
  }

  void cut_pimpl::
  data (const std::string& data)
  {
    // TODO
    //
  }

  void cut_pimpl::
  comment (const std::string& comment)
  {
    // TODO
    //
  }

  void cut_pimpl::
  cut_id (unsigned int cut_id)
  {
    // TODO
    //
  }

  void cut_pimpl::
  datetime (const std::string& datetime)
  {
    // TODO
    //
  }

  ::tmxsd::cut cut_pimpl::
  post_cut ()
  {
    // TODO
    //
    // return ... ;
  }
}

