// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "simple-types-pimpl.hh"

#include <iostream>

namespace tmxsd
{
  // id_pimpl
  //

  void id_pimpl::
  pre ()
  {
  }

  unsigned int id_pimpl::
  post_id ()
  {
    return post_unsigned_int ();
  }

  // uuid_pimpl
  //

  void uuid_pimpl::
  pre ()
  {
  }

  std::string uuid_pimpl::
  post_uuid ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // datetime_pimpl
  //

  void datetime_pimpl::
  pre ()
  {
  }

  std::string datetime_pimpl::
  post_datetime ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // real_pimpl
  //

  void real_pimpl::
  pre ()
  {
  }

  std::string real_pimpl::
  post_real ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // char64_pimpl
  //

  void char64_pimpl::
  pre ()
  {
  }

  std::string char64_pimpl::
  post_char64 ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // char1k_pimpl
  //

  void char1k_pimpl::
  pre ()
  {
  }

  std::string char1k_pimpl::
  post_char1k ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // char4k_pimpl
  //

  void char4k_pimpl::
  pre ()
  {
  }

  std::string char4k_pimpl::
  post_char4k ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }
}

